name: Image Minimizer

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

permissions:
  contents: read
  # write permission is not required as FOSSIFYBOT_TOKEN is used

jobs:
  call-image-minimizer-workflow:
    uses: FossifyOrg/.github/.github/workflows/image-minimizer.yml@main
    secrets:
      FOSSIFYBOT_TOKEN: ${{ secrets.FOSSIFYBOT_TOKEN }}
