name: Image Minimizer

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

jobs:
  call-image-minimizer-workflow:
    uses: FossifyOrg/.github/.github/workflows/image-minimizer.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
