name: No Response

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at noon
  workflow_dispatch:

jobs:
  call-no-response-workflow:
    uses: FossifyOrg/.github/.github/workflows/no-response.yml@main
    with:
      days_before_close: 14
      stale_label: 'waiting for author'
    secrets:
      FOSSIFYBOT_TOKEN: ${{ secrets.FOSSIFYBOT_TOKEN }}