name: Testing build (on PR)

on:
    pull_request:
        branches: [ $default-branch ]
        types: [ labeled, opened, synchronize, reopened ]

jobs:
    call-testing-build-workflow:
        uses: FossifyOrg/.github/.github/workflows/testing-build.yml@main
        # The following keys can be used to change defaults
        # with:
        #     build_task: 'aseemblePrepaidDebug'
        #     expected_label: 'testers needed'
