name: no-response

on:
  workflow_call:
    inputs:
      days_before_close:
        description: "Number of days of inactivity before an issue is closed for lack of response"
        type: number
        default: 14
        required: false
      days_before_issue_close:
        description: "Number of days of inactivity before an issue is closed for lack of response"
        type: number
        default: 14
        required: false
      days_before_pr_close:
        description: "Number of days of inactivity before a PR is closed for lack of response"
        type: number
        default: 24
        required: false
      stale_label:
        description: "Label to use for marking issues that are waiting for a response"
        type: string
        default: "waiting for author"
        required: false

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: naveensingh/stale@v9.2.0
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          days-before-stale: -1
          days-before-close: ${{ inputs.days_before_close }}
          days-before-issue-close: ${{ inputs.days_before_issue_close }}
          days-before-pr-close: ${{ inputs.days_before_pr_close }}
          only-labels: ${{ inputs.stale_label }}
          stale-issue-label: ${{ inputs.stale_label }}
          stale-pr-label: ${{ inputs.stale_label }}
          close-issue-label: invalid
          remove-stale-when-updated: false
          ignore-updates: true
          close-issue-message: This issue was automatically closed due to inactivity and/or lack of response from the author. If additional information becomes available, please leave a comment to reopen the issue.
          close-pr-message: This pull request was automatically closed due to inactivity and/or lack of response from the author. If you have further updates or additional information, please comment or reopen the PR to continue.
