name: PR Labeler

on:
  workflow_call:

jobs:
  label-prs:
    name: "Label PRs"
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Label l10n PRs
        if: |
          contains(github.event.pull_request.title, 'l10n') ||
          contains(github.event.pull_request.user.login, 'weblate')
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          labels: l10n

      - name: Label i18n PRs
        if: contains(github.event.pull_request.title, 'i18n')
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          labels: i18n

      - name: Label CI PRs
        if: |
          contains(github.event.pull_request.title, 'ci:') ||
          contains(github.event.pull_request.title, 'ci(')
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          labels: ci

      - name: Label Documentation PRs
        if: |
          contains(github.event.pull_request.title, 'docs:') ||
          contains(github.event.pull_request.title, 'docs(')
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          labels: documentation
