name: Release Commenter

on:
  workflow_call:

jobs:
  releaseCommenter:
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: apexskier/github-release-commenter@3bd413ad5e1d603bfe2282f9f06f2bdcec079327
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          label-template: "released"
          skip-label: "ci,dependencies,documentation,l10n,i18n,released"
          comment-template: ""
