name: Fastlane metadata validation

on:
  workflow_call:

jobs:
  fastlane:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Checkout .github repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: FossifyOrg/.github
          path: .github-repo

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: "3.x"

      - name: Run metadata validator
        run: python ./.github-repo/scripts/validate_fastlane_metadata.py
